### ISSUE TITLE
KotlinPoet wrongly inlines extension functions

### ISSUE THREAD

**Issue by oldergod** [square/kotlinpoet#1089]
KotlinPoet seems to be inlining extensions functions like if they were members and this generates non-compilable code.

Here's a diff of our before/after.

```diff
 import kotlin.Long
 import kotlin.String
 import kotlin.Unit
-import kotlin.hashCode
 import kotlin.jvm.JvmField
 import okio.ByteString

@@ -55,8 +54,8 @@ public class OuterMessage(
     var result = super.hashCode
     if (result == 0) {
       result = unknownFields.hashCode()
-      result = result * 37 + outer_number_before.hashCode()
-      result = result * 37 + embedded_message.hashCode()
+      result = result * 37 + outer_number_before.kotlin.hashCode()
+      result = result * 37 + embedded_message.kotlin.hashCode()
       super.hashCode = result
     }
     return result
```

It breaks Wire when we bump KotlinPoet from `1.7.2` to `1.8.0`.
I think that's a side-effect of https://github.com/square/kotlinpoet/pull/1040 ?

**Comment by Egorand** [comment]
Yeah, that's likely the cause.. However I don't think there's anything we can do, the behavior is correct - there is a method with the same name in scope, so we have to use the fully-qualified imported function name to disambiguate. This doesn't work well with extension functions though, and currently there's no way to know whether a `MemberName` is used as an extension. I wonder if we should try adding something like `MemberName.isExtension` to gate this logic. For the time being though, I'd suggest adding the `kotlin.hashCode` import manually (through `FileSpec.addImport`) and using "hashCode" as a plain string instead of `MemberName` when generating relevant code.
