### ISSUE TITLE
Redundant visibility modifier should not be generated

### ISSUE THREAD

**Issue by babyfish-ct** [square/kotlinpoet#1205]
1. "public" should not be generated for public types.
2. "public" should not be generated for the members of interface.
3. "public" should not be generated for public members.

Now, my work around is 
```
addAnnotation(
    AnnotationSpec
        .builder(Suppress::class)
        .apply {
            addMember("\"RedundantVisibilityModifier\"")
        }
        .build()
    )
```
but I still hope it will fixed and generate cleaner code for users

**Comment by JakeWharton** [comment]
KotlinPoet generates code which supports explicit API mode: https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors

There is no way to disable this because the code generator and the compilation task are configured separately meaning a code generator has no way to know whether it needs to support this mode or not. Ergo, we always support it.

**Comment by sschuberth** [comment]
> a code generator has no way to know whether it needs to support this mode or not. Er

The code generator doesn't, but the user who configures the code generator does. Ergo, there should be an API option to disable redundant visibility modifiers.

**Comment by JakeWharton** [comment]
We will not be offering such an option, sorry.
