### ISSUE TITLE
Mark an immutable property as inline

### ISSUE THREAD

**Issue by tadfisher** [square/kotlinpoet#1217]
The documentation suggests the following snippet to generate an `inline val` property:

```kotlin
val android = PropertySpec.builder("android", String::class)
    .getter(FunSpec.getterBuilder()
        .addModifiers(KModifier.INLINE)
        .addStatement("return %S", "foo")
        .build())
    .setter(FunSpec.setterBuilder()
        .addModifiers(KModifier.INLINE)
        .addParameter("value", String::class)
        .build())
    .build()
```

This results in the error message `only a mutable proeprty can have a setter`, which makes sense. However, without adding a setter, the snippet above generates:

```kotlin
val android: String
    inline get() = "foo"
```

Which is not the expected

```kotlin
inline val android: String
    get() = "foo"
```

Now, I don't know if the two declarations above have a meaningful difference in the Kotlin compiler output. If not, it seems to me that inlining a getter on an immutable property should just inline the property. If so, perhaps it would be acceptable to declare `KModifier.INLINE` on the `PropertySpec.Builder` itself, and throw the error when emitting a mutable property.

**Comment by Egorand** [comment]
Ah, that's definitely a bug with the documentation, thanks for catching! I think there are two things to fix:

- The documentation snippet should be building a `var` instead of a `val`, by adding a `mutable(true)` call to the builder
- The library should probably emit an `inline val` if you're marking the getter `INLINE` on an immutable property

As for allowing `INLINE` on the property itself, the documentation provides the justification for why we decided to disallow this.

Please feel free to send us PRs!
