### ISSUE TITLE
Specify exact output path for files

### ISSUE THREAD

**Issue by terminalnode** [square/kotlinpoet#1348]
When using `file.writeTo(path)` the root package is always added to the output path, e.g. `path/com/example/subpackage`, and from what I've found it's not possible to specify the exact path to put the file.

This is a reasonable default. In java this structure would be required, but in kotlin package names don't have to match the folder structure and IntelliJ supports infering the root package from the package used in the sources root. E.g. if you have a file `src/main/kotlin/Main.kt` with package `com.example.test`, it will infer that the package for `src/main/kotlin/sub/Sub.kt` should be `com.example.test.sub`.

It may be tricky to have kotlinpoet infer packages like this, but it would be nice to have the option to specify the full path explicitly, and have kotlinpoet not append the folderstructure.

The best option in my opinion would be to not convert `File` to `Path` in `writeTo`, but use that as an actual output file. But such a change to the API may not be desirable, so the second best option I think would be some option on whether to add the root package name, e.g. something like this:
```kt
val path = Path.get(project.projectDir.absolutePath, "src/main/kotlin/sub")

// Write file to src/main/kotlin/sub
file.writeTo(path, useExactPath = true)

// or, current behavior, write file to src/main/kotlin/com/example/sub
file.WriteTo(path) // useExactPath defaulting to false to keep curret behavior
```

**Comment by JakeWharton** [comment]
Since we have the full package information available, what is the motivation to generate files in this way? My understanding was that it was for humans who didn't want to deal with the deeply nested folder structure (not that you ever do that anyway if you're in an IDE). I'm struggling on seeing a reason as to why someone would choose this when the source files are the output of a code generator and the input of the Kotlin compiler (which doesn't care).

**Comment by terminalnode** [comment]
> My understanding was that it was for humans who didn't want to deal with the deeply nested folder structure

That is the purpose here as well. It's true that the IDE will treat `com/example/` as a single folder, as will GitHub, but sometimes for whatever reason you need or want to to navigate the file structure in a terminal or file browser.

> I'm struggling on seeing a reason as to why someone would choose this when the source files are the output of a code generator and the input of the Kotlin compiler (which doesn't care).

In the project I'm working on the generated files are only part of the project, not the whole project. So the convenience of easily navigating the folder structure still matters for working on the files that aren't generated.

**Comment by JakeWharton** [comment]
This assumes that you control the code generator, though. We generally don't offer APIs like this because ultimately you don't control every code generator and one will do something that you don't expect (wrong indents, wrong folder structure, whatever).

Can you apply this as a post-processing step? It seems like you can traverse the output directory until you find the first folder that has more than one subfolder or a file and then move its contents to the root.

**Comment by terminalnode** [comment]
How do you mean not control the code generator? E.g. if the code is generated by a plugin maintained by someone else? In most cases I would think that such a thing should be the developer's responsibility.

Another, perhaps safer than my previous suggestions, would be to have an option for simply removing a part of the path.

```kt
val path = Path.get(project.projectDir.absolutePath, "src/main/kotlin")
file.WriteTo(path, removePrefix="com.example")
```

So when KotlinPoet sees a package with the name of `com.example.sub`, for the purposes of folder structure it will treat it as if the package is just `sub`, and perhaps do a sanity check to see that `com.example` is actually part of the package name.

> Can you apply this as a post-processing step? It seems like you can traverse the output directory until you find the first folder that has more than one subfolder or a file and then move its contents to the root.

I think that would work, though at that point I'd probably rather just refactor it to use the proposed folder structure.

**Comment by JakeWharton** [comment]
> How do you mean not control the code generator? E.g. if the code is generated by a plugin maintained by someone else? In most cases I would think that such a thing should be the developer's responsibility.

Almost every code generator I use is maintained by someone else at the company or by a completely different company. Just because I want something from what they generate doesn't necessarily mean they're going to honor my wishes.

> Another, perhaps safer than my previous suggestions, would be to have an option for simply removing a part of the path.
>
> ```kotlin
> val path = Path.get(project.projectDir.absolutePath, "src/main/kotlin")
> file.WriteTo(path, removePrefix="com.example")
> ``` 
>
> So when KotlinPoet sees a package with the name of com.example.sub, for the purposes of folder structure it will treat it as if the package is just sub, and perhaps do a sanity check to see that com.example is actually part of the package name.

Yes I started replying with this as a suggestion but backed away from it upon further thought.

It requires that either the code generator know ahead of time the root package which is unlikely, or it has to compute it based on inputs (in which case walking the output folder and moving the contents of the first folder with >1 child to the root seems much simpler). It also means we have to design what happens when you emit a file into a package which does not match the specified prefix. Do we throw an exception? Do we write it to the proper qualified path? It's a problem that simply doesn't exist if we always write the full package path.

**Comment by terminalnode** [comment]
This all sort of makes sense if most use-cases don't know the package ahead of time. What I don't understand is why an option, which you do not have to use if it doesn't match your use-case (e.g. generating code for use by a different company or project), would be excluded on these grounds?

I think an exception is most definitely the correct answer on what to do is the path doesn't match. The application has received an instruction on which it can't act, guessing is just gonna make things worse. A clear error message would be the way to go. I also noticed there's a DelicateApi-annotation on some things, which would be fitting for this use-case.

**Comment by JakeWharton** [comment]
> What I don't understand is why an option, which you do not have to use if it doesn't match your use-case (e.g. generating code for use by a different company or project), would be excluded on these grounds?

In general we try to leave out features that don't serve a majority of users from the core of the library and try to look at ways to enable accomplishing your goal but without taking on the complexity ourselves. Jesse and I gave a talk many years ago which talks about it: https://youtu.be/PCxz2LEmuL4&t=1643s

This calls back to the reason we don't offer control over the indent style or someone recently wanted the ability to change the newline endings. These things serve the ergonomics of humans but the tool is primarily designed to target compilers where these things don't matter. We still try to make the generated code look nice for when you have to debug into it, but stylistic treatments like the indent type, newline char, or folder structure aren't open for customization because we don't believe it plays a meaningful part in the ability to understand the output.

**Comment by Egorand** [comment]
I'm gonna close this issue as it doesn't seem like we'll be taking any action here. Please feel free to reopen if necessary!

**Comment by okamo1984** [comment]
I have this issue because my package is not compatible to directory structure. The following workaround is found.

```kotlin
fun write(outPath: Path, file: FileSpec) {
    Files.createDirectories(outPath.parent)
    OutputStreamWriter(
        Files.newOutputStream(outPath),
        StandardCharsets.UTF_8
    ).use { writer -> file.writeTo(writer) }
}
```
