### ISSUE TITLE
Consider adding more formatting options

### ISSUE THREAD

**Issue by snicoll** [square/kotlinpoet#1560]
**Is your feature request related to a problem? Please describe.**
We're considering using JavaPoet and KotlinPoet in a getting started service and code formatting is very important for us. The sample in the reference guide looks like this:

```kt
class Greeter(val name: String) {
  fun greet() {
    println("""Hello, $name""")
  }
}

fun main(vararg args: String) {
  Greeter(args[0]).greet()
}
```

We'd like it to be more like this:

```kt
class Greeter(val name: String) {

  fun greet() {
    println("""Hello, $name""")
  }

}

fun main(vararg args: String) {
  Greeter(args[0]).greet()
}
```

There is a notion of `indent` and I was wondering if you'd be open to deprecate it in favor of a more generalized solution where an implementation can have control on how things are organized in the source code. We've investigated running a formatter as part of the generation process but we have support for Java, Kotlin, and Groovy so embedding all of that doesn't sound fun.

**Describe the solution you'd like**
A new API that can be provided the same `indent` is now where we have more control over spacing and file organization.

**Describe alternatives you've considered**
Running code formatters using spotless.

**Additional context**
None.

**Comment by Egorand** [comment]
I don't think the value to complexity ratio of this API will be positive to be honest. Your use case feels quite specific, and I believe KotlinPoet's built in formatting plus formatter tools satisfy the vast majority of use cases. I'd probably recommend sticking with formatter tools that are purpose-built for this task and can be tuned to your liking.

**Comment by ZacSweers** [comment]
I think the right solution is for your to post-process the written file with the formatter of your choice

**Comment by JakeWharton** [comment]
We should probably write that down somewhere as our formal recommendation. Or maybe we already have?

Formatting has a really long tail of desire for customization. We will forever be chasing and trying to balance the defaults and granularity of controls to satisfy everyone's needs. We try to only include what's necessary for everyone, and leave out almost everything else

Jesse and I gave a talk on this nearly a decade ago, and it's a philosophy that's shaped nearly all of our libraries: https://youtu.be/PCxz2LEmuL4?t=1643.

Frankly, we shouldn't have even supported indent! The only indent you need is tabs, because a correctly configured `.editorconfig` will render those using your preferred spacing.
