### ISSUE TITLE
Import aliases for conflicting imports can mess up type names for members

### ISSUE THREAD

**Issue by jdm-square** [square/kotlinpoet#1563]
**Describe the bug**

When import aliases are generated for conflicting types, they seem to overwrite usages of members of the original types that are aliased. This means that if there are two conflicting usages of `Message` classes (`packageA.first.Message` and `packageB.second.Message`), we get two `FirstMessage` and `SecondMessage` import aliases. However, if the uses of `Message` look like `packageA.first.Message.Builder` and `packageB.second.Message.Builder`, these uses get rewritten as `FirstMessage` and `SecondMessage` and the reference to `.Builder` is lost.

**To Reproduce**

```
  @Test fun conflictingImportsWithMember() {
    val source = FileSpec.builder("com.squareup.tacos", "Taco")
      .addType(
        TypeSpec.classBuilder("Taco")
          .addProperty("madeFreshDate", ClassName("java.util", "Date", "Builder"))
          .addProperty("madeFreshDatabaseDate", ClassName("java.sql", "Date", "Builder"))
          .build(),
      )
      .build()
    assertThat(source.toString()).isEqualTo(
      """
        |package com.squareup.tacos
        |
        |import java.sql.Date as SqlDate
        |import java.util.Date as UtilDate
        |
        |public class Taco {
        |  public val madeFreshDate: UtilDate.Builder
        |
        |  public val madeFreshDatabaseDate: SqlDate.Builder
        |}
        |
      """.trimMargin(),
    )
  }
```

Resuts:
```
expected:
    …eFreshDate: UtilDate.Builder
    
      public val madeFreshDatabaseDate: SqlDate.Builder
    }
    
but was:
    …eFreshDate: UtilDate
    
      public val madeFreshDatabaseDate: SqlDate
    }
```

**Expected behavior**

The alias should rewrite the conflicting use but not any subsequent context.

**Additional context**
This was exposed by code in the Wire project.

**Comment by Egorand** [comment]
Submitted a fix, thanks for the detailed bug report!

Worth noting that the bug was not introduced by the auto-generated import aliases feature, rather, this feature likely surfaced an old bug: I imagine that before the feature was introduced, the test case above would simply emit fully-qualified type names, which would pass compilation. If the code supplied import aliases manually via `FileSpec.addAliasedImport`, as demonstrated by one of the tests added in #1568, output would be the same.

As a temporary workaround, you might try manually adding import aliases for the `Builder`s using the method mentioned above.
