### ISSUE TITLE
Do not apply the line length limit to CodeBlock

### ISSUE THREAD

**Issue by OndraZizka** [square/kotlinpoet#1566]
**Describe the bug**
KotlinPoet cuts CodeBlock in half, causing invalid syntax.
CodeBlock is meant for the free pieces of code.
If it contains a string literal, the lines are very prone to being cut in half, causing uncompilable code. 

**To Reproduce**
```kotlin
CodeBlock.of("""println("Class: $className")""")
```

If the class has really long name, KotlinPoet generates an invalid code:

```
prinln("Class:
very.long.class.name.Here")
```

**Expected behavior**
1) CodeBlock should ignore the line length limit.
2) The line length limit should be configurable. That's covered in #1020 . 

**Additional context**
120 developers would be very grateful if the line length is configurable.

**Comment by JakeWharton** [comment]
To be clear here, the bug is that we perform breaking within a string. That should not happen.

I'm not going to entertain changing the line limit or not applying it to code blocks in this specific issue.

**Comment by Egorand** [comment]
The library doesn't know that the `"Class: $className"` segment is in fact a string (since all `CodeBlock` arguments are strings, but not all of them translate to string values in generated code), so it wraps the space. Use `%S` to get around it (source: [%S for Strings](https://square.github.io/kotlinpoet/#s-for-strings)):

```kotlin
CodeBlock.of("""println(%S)""", "Class: $className")
```

You also have the option of using the `·` character to mark non-wrapping spaces (as described in [Spaces wrap by default!](https://square.github.io/kotlinpoet/#spaces-wrap-by-default)), but in this case I'd recommend using `%S`.

**Comment by OndraZizka** [comment]
@Egorand  @JakeWharton  thanks. I suggest to add this example to the documentation somewhere near the spaces wrap, as the way to solve this issue.

**Comment by Egorand** [comment]
Done! #1576
