### ISSUE TITLE
Why not support generate the body of method by using modeled api?

### ISSUE THREAD

**Issue by zhoujia1993** [square/kotlinpoet#1706]
I have a need to translate a JS-like language into kotlin source code. I will traverse the AST of that language and use kotlinpoet's api to generate kotlin source code, but I find that kotlinpoet's method can only support string descriptions. This prevented me from doing a good job of converting methods.

I would like to know why kotlinpoet does not support modeled method descriptions, and would it consider supporting them.

Now I can only consider using the open source library 'JavaParser’ or investigating if I can implement my own generation logic based on kotlin AST.

**Comment by JakeWharton** [comment]
Simply put because there are too many shapes to what can be placed in the body of a function as opposed to how files and types can be structured. The API surface would explode tenfold, if not more. We would have to constantly be tracking a ridiculous amount of detail in what is possible to represent in code vs. what is invalid. The API would effectively become a subset of the Kotlin compiler.

We don't want to design that, or maintain that.

KotlinPoet, and JavaPoet before it, are about two things: conveniently modeling the structure of your files so that types are easier to piece together from parts, and automatically importing any required types that you reference. Other than that, once we reach the body of methods or functions we want to be as hands-off as possible. This means that as the meat of the language evolves, we don't have to do anything to allow you to use these new features. It makes both of our lives easier in the end.

Since we ultimately take strings, you are free to create or use some other mechanism of modeling the contents of function bodies so long as it renders to strings (or `CodeBlock`s). We simply don't want to be in that business.
