### ISSUE TITLE
com.squareup:kotlinpoet 1.15.3 missing class files.

### ISSUE THREAD

**Issue by deweyjose** [square/kotlinpoet#1798]
**Describe the bug**
The published artifact for com.squareup:kotlinpoet version 1.15.3 on maven central looks to be corrupt? I don't see any class files.

<img width="434" alt="image" src="https://github.com/square/kotlinpoet/assets/15958124/68eea435-4165-4cc8-bea7-73fe9586951f">

The published artifact on for Version 1.14 maven central does though. 

<img width="497" alt="image" src="https://github.com/square/kotlinpoet/assets/15958124/e7bb9434-bd9a-4a55-9d53-b0b919969711">

I manage an open project that provides a Maven build plugin for GraphQL code generation library managed by Netflix. It is a thin maven wrapper over their core [dgs codegen library](https://github.com/Netflix/dgs-codegen). It looks like they recently upgraded to kotlinpoet 1.15.3: https://github.com/Netflix/dgs-codegen/releases/tag/v6.1.1
 
We're now seeing the following when we run our maven plugin:

```
[ERROR] Failed to execute goal io.github.deweyjose:graphqlcodegen-maven-plugin:1.51.2:generate (default) on project client: Execution default of goal io.github.deweyjose:graphqlcodegen-maven-plugin:1.51.2:generate failed: A required class was missing while executing io.github.deweyjose:graphqlcodegen-maven-plugin:1.51.2:generate: com/squareup/kotlinpoet/TypeNames
```

**To Reproduce**

Add the following to a pom file 

```xml
<dependency>
            <groupId>com.squareup</groupId>
            <artifactId>kotlinpoet</artifactId>
            <version>1.15.3</version>
</dependency>
```

**Expected behavior**

**Additional context**

**Comment by JakeWharton** [comment]
If you are using Maven or any other non-Gradle build system you must now depend on `kotlinpoet-jvm`. This is because the library became multiplatform so that in the future those who want to run their code generation from JS, native, or WASM can do so.

The README was updated, but I believe we failed to call it out sufficiently in the release notes now that I think about it.

**Comment by deweyjose** [comment]
Hi @JakeWharton  - appreciate the quick follow up. I'll give this a try right now.

**Comment by deweyjose** [comment]
That did the trick. Thanks again @JakeWharton !

**Comment by kylepl** [comment]
As another person that just ran into this, and definitely not a Kotlin/Java expert, I'm wondering if it makes sense to no longer publish to Maven - since the versions are ~empty (e.g. https://repo1.maven.org/maven2/com/squareup/kotlinpoet/1.15.0/). My thinking is non-existant versions would be better than existant-but-empty.

**Comment by JakeWharton** [comment]
The unqualified artifact name version is what contains the Gradle module metadata that allows resolving to the correct platform variant. The real problem is that we should be publishing the JVM platform as the default variant at those coordinates (or at least make it a dependency of that artifact).
