### ISSUE TITLE
Wrapping and indentation is strange when hitting the 100 characters bound

### ISSUE THREAD

**Issue by Vampire** [square/kotlinpoet#1970]
This `main.kts` script:
```kotlin
#!/usr/bin/env kotlin

@file:DependsOn("com.squareup:kotlinpoet-jvm:1.18.1")

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec

buildString {
    val indentSize = 4
    val quoteSize = 1
    val skipOverSize = 100 - (2 * indentSize) - (2 * quoteSize)
    FileSpec
        .builder("", "Test")
        .addFunction(
            FunSpec
                .builder("test")
                .addCode(
                    """
                        require(false) {
                            %S
                        }
                        require(false) {
                            %S
                        }
                    """.trimIndent(),
                    (1..skipOverSize).joinToString("") { "." },
                    (1..(skipOverSize + 1)).joinToString("") { "." }
                )
                .build()
        )
        .indent((1..indentSize).joinToString("") { " " })
        .build()
        .writeTo(this)
}
```
produces
```kotlin
public fun test() {
    require(false) {
        ".........................................................................................."
    }
    require(false) {
       
            "..........................................................................................."
    }
}
```
But imho it would be nicer if it produces
```kotlin
public fun test() {
    require(false) {
        ".........................................................................................."
    }
    require(false) {
        "..........................................................................................."
    }
}
```
In the current version there is a blank line with 7 spaces and then the double-indented string.

**Comment by JakeWharton** [comment]
This is because when the limit is exceeded the library walks backwards, breaks at the first space, and replaces it with a newline. The library doesn't parse the content of your code so this behavior is basically working as intended, albeit perhaps unexpected.

If you instead use `beginControlFlow` for the `require`, `addStatement` for the string, and `endControlFlow` it shouldn't do this. But for giant blocks of code the library doesn't understand what's in them and will do simple things.

Formatting is best effort. All we really care about is that it compiles. There's an issue for removing the line break strategy completely since it can change program semantics.

If you care deeply about the formatting of the output we recommend post-processing with a dedicated formatter.

**Comment by Vampire** [comment]
I see, thanks.
I guess the issue you mean is #1314?
And from the comments I guess there is currently neither a way to disable the wrapping
nor to set the line length to `MAX_VALUE`?

> All we really care about is that it compiles. 

Which it not always does. :-D
In another spot I got `foo to bar` wrapped before the `to` making it non-compilable, but the found the middot trick. :-)

**Comment by Egorand** [comment]
> In another spot I got `foo to bar` wrapped before the `to` making it non-compilable, but the found the middot trick. :-)

That's what #1314 should address, wrapping should be opt in rather than opt out!
