### ISSUE TITLE
KotlinPoet 1.0 wishlist

### ISSUE THREAD

**Issue by swankjesse** [square/kotlinpoet#233]
* [ ] ~Magic to map JVM types like `java.lang.Integer`/`java.util.List` to Kotlin types like `kotlin.Int`/`kotlin.collections.List`. Similar to [#152](https://github.com/square/kotlinpoet/pull/152).~
*  [x] Improve README (see JavaPoet) (#337)

**Comment by Takhion** [comment]
@swankjesse I can help with that :)

**Comment by swankjesse** [comment]
Thanks for volunteering @Takhion. @Egorand and I looked into this a few months ago and it turns out that it’s a decent amount of work to build the mapping from JVM types to the corresponding Kotlin types. The mapping needs to know if the types are mutable also, so Java’s List maps to both Kotlin’s List and its MutableList.

Plus the mapping changes with each Kotlin release.

**Comment by JakeWharton** [comment]
You can help with the reflect and model APIs to parse the metadata though
to create accurate TypeNames for those APIs.

**Comment by Takhion** [comment]
@swankjesse like @JakeWharton said, I've already done this work by deferring the actual mapping to the Kotlin compiler classes :)

I'm in the middle of refactoring my library to parse Kotlin metadata, I'll make sure to expose this functionality so it can be used by kotlinpoet 🙌 

P.S. I'm thinking of creating a series of utils to translate Kotlin types/elements directly to kotlinpoet constructs, which would be very useful for generating code based on existing Kotlin code!

**Comment by swankjesse** [comment]
Oh hell yes! That'd be awesome.

**Comment by jdemeulenaere** [comment]
I guess that the new [kotlinx-metadata-jvm](https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ReadMe.md) could be useful for that as well.

**Comment by hzsweers** [comment]
Eventually yes, but it's got a few bugs that prevent it from being usable right now

**Comment by Egorand** [comment]
I tried using @Takhion's library in KotlinPoet, and the thing I struggled with is that the way our API is designed, in most cases it's hard to get access to the metadata and use it effectively, since the context is usually missing. For example, the following:

```
MutableMap::class.asTypeName()
```

Will currently print `kotlin.collections.Map`, which is incorrect. If I'm able to access the metadata for the code element that uses this type, then I can find the correct type, but the actual challenge is figuring out that code element. There's no way to get access to this data from `asTypeName()`. 

`kotlinx-metadata-jvm` would work well in the context of an annotation processor (Moshi Kotlin codegen is a great example), but I'm not sure how it should be used in KotlinPoet. Maybe the right way to go is to complement KotlinPoet with an annotation processor that could be used as a base for other processors and can use the metadata to fix some of the issues we have.

**Comment by hzsweers** [comment]
I'm kind of thinking it maybe shouldn't be a requirement for 1.0 due to the new first party library in the future and the sort of lack of clarity aorund how to proceed right now. If anything, it seems like it could almost be a separate project or artifact of extension functions anyway.

From a high level, in traditional cases you'd need to supply context for a type to read the metadata off it, which could prove difficult to make a sane API around.

**Comment by Egorand** [comment]
Removed the Kotlin type conversion magic from the list and closing.
