### ISSUE TITLE
JavaPoet Interop

### ISSUE THREAD

**Issue by ShaishavGandhi** [square/kotlinpoet#417]
This is more of a question/feature suggestion. I'm working on a project where I'm using both JavaPoet and KotlinPoet (JavaPoet for some code and then Kotlin extensions that make the API sweeter for Kotlin users). 

One thing that I really wished for would be mapping between JavaPoet and KotlinPoet using extension functions. Possible use-cases would be to map between JavaPoet's `ClassName` and KotlinPoet's `ClassName` with something like `com.squareup.javapoet.ClassName.toKClassName()` which will give you the corresponding KotlinPoet `ClassName`. This would be similar for parameters, methods etc and give library developers a very easy path to write Kotlin extensions for their annotation processing libraries with minimal change to their existing codebase.

**Comment by JakeWharton** [comment]
With types you should always be able to go from Java to Kotlin, but you cannot losslessly go in the opposite direction without losing nullability information. We could allow optionally supplying a Java `ClassName` for each of a nullable and non-null type-parameter-capable annotation or that information would have to just be lost.

I don't really see a path for doing this with anything else like methods or parameters. The languages have entirely different constructs for those such that it doesn't map one-to-one. For example, you might generate a pair of methods for Java which are overloads whereas in Kotlin you would generate a single method with a parameter that has a default.

**Comment by shaishavgandhi05** [comment]
That's true. It would be a huge undertaking to convert from Java to Kotlin especially since the languages are really different in a lot of places. 

What do you think about having extensions to actually give you the builders instead of the ParameterSpec/MethodSpec? For example, the extension would do a "dumb" convert to corresponding Kotlin `ParameterSpec.Builder`/`MethodSpec.Builder` without any of Kotlin's language features. It would then be up to the developer to take advantage of default values, overloads etc. The aim is to give a base to build on. 

To further explain the motivation behind what may seem like a tangential feature request is that sometimes, the code generation is littered with strong references to JavaPoet and it's constructs and with hardly any abstraction (for example I had a HashMap of `ClassName` to set of annotations). Admittedly, this is just wrong software practice and we should abstract our code from the library, but considering that JavaPoet is a very popular library for Java code generation, I think the number of people with that same abstraction problem is non-trivial.

**Comment by swankjesse** [comment]
Maybe write some extension functions to map from JavaPoet types to their KotlinPoet equivalents?

**Comment by shaishavgandhi05** [comment]
Yeah that was my plan. Was just wondering if that would be a useful addition to KotlinPoet.

**Comment by swankjesse** [comment]
I’m reluctant to add integration at the moment. Maybe share a gist or a standalone GitHub project? If it gathers interest we can make a plan.

**Comment by shaishavgandhi05** [comment]
That sounds good! Thanks.

**Comment by ShaishavGandhi** [comment]
Following up on this: At Uber, we had a bunch of extensions that did interop between JavaPoet <-> KotlinPoet. Happy to upstream that if anyone's interested!

**Comment by ShaishavGandhi** [comment]
Here are the extensions in a gist:
https://gist.github.com/ShaishavGandhi/097033cc528ae25741186973e4d36ce4

**Comment by AdamMTGreenberg** [comment]
@ShaishavGandhi super useful, thanks!
