### ISSUE TITLE
Allow using TypeSpec as TypeNames

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [square/kotlinpoet#444]
It would already be useful if you'd add `TypeSpec.asTypeName`, but it'd be more useful if you'd add an overloaded version using `TypeSpec` to each method accepting `ClassName`, `KClass` etc

**Comment by JakeWharton** [comment]
A TypeSpec doesn't know it's package. Only it's name.

**Comment by kaeptmblaubaer1000** [comment]
@JakeWharton I've seen this after creating this issue, but I've always created `TypeSpec`s with a `ClassName`, so I've just expected that it is storing the package.

**Comment by Egorand** [comment]
Yeah, the overloads with `ClassName` parameters are for convenience only, internally we just call the factory method with the `String` param passing `className.simpleName`. Don't think we want to be keeping `className` around. Plus what Jake said, even if you'd call `TypeSpec.asTypeName` you can't expect it to give you a fully-qualified class name that you used to create it, since the `TypeSpec` is not supposed to know its package.
