### ISSUE TITLE
Make "Builder" and "Built" types more symmetric

### ISSUE THREAD

**Issue by LouizFC** [square/kotlinpoet#602]
Often I need to access a `Builder` name before "building" it.

Problem is, most if not all `Builder`s have their name as `internal`. I understand that the name is easely availiable if I `#build()` the Spec, but I am opening this just to know if its something worth working on.

There are some other nit picks like TypeSpec having `isEnum`, `isCompanion`, etc and `TypeSpec.Builder` having them as `internal`.

Is that something that got overlooked because of the very niche use case or some design decision?

**Comment by Egorand** [comment]
Since `Builder` classes represent mutable entities, we want to avoid exposing their internal representation unless there's a very good reason for it. On the flip hand, Specs are immutable, so most of their members are public. You can do the following:
```kotlin
val builder = TypeSpec.classBuilder("Tacos")
    .build()
    .let { spec ->
      val name = spec.name
      // do something with name
      return@let spec.toBuilder()
    }
```
It's not ideal since it'll require unnecessary allocations, but it's fine for one-off cases.

**Comment by LouizFC** [comment]
Understandable. Thank you very much @Egorand
