### ISSUE TITLE
Non package classes are wrongly imported

### ISSUE THREAD

**Issue by shaishavgandhi05** [square/kotlinpoet#645]
I think this change (https://github.com/square/kotlinpoet/pull/636) was a breaking change for consumers. 

After upgrading to latest SNAPSHOT, I'm seeing issues of class names that are wrongly imported in the file. This is evident from the changes in the tests that were made in that PR. All instances of `ClassName.bestGuess()` were replaced with `ClassName(package, className)`. Take this example:

```kotlin
@Test fun test() {
    val funSpec = FunSpec.builder("getRandomInt")
        .returns(ClassName.bestGuess("IntArray"))
        .build()

    val file = FileSpec.builder("com.example", "MyFileName")
        .addFunction(funSpec)
        .build()

    assertThat(file.toString()).isEqualTo("""
      |package com.example
      |
      |import IntArray // Compilation error
      |
      |fun getRandomInt(): IntArray {
      |}
      |""".trimMargin())
  }
```

In this case, `IntArray` is wrongly imported and causes compile time failures. In fact, `IntArray` shouldn't be imported since it's a default package that's imported. 

This might be a trivial example since I can obviously pass along the package name, but there are instances where you might not have the package name access. 

I'd propose reverting the change till we find a better, non-breaking solution.

**Comment by JakeWharton** [comment]
KotlinPoet doesn't honor default imports. `ClassName.bestGuess("IntArray")` is synonymous with `ClassName("", "IntArray")` and so that test looks valid and correct from KotlinPoet's perspective despite being semantically incorrect from Kotlin's.

**Comment by JakeWharton** [comment]
If you wanted that test to be semantically correct, either `ClasName.bestGuess("kotlin.IntArray")` or `ClassName("kotlin", "IntArray")` should be used.

**Comment by shaishavgandhi05** [comment]
Yes I agree that including the package name is required for `bestGuess` to work correctly and my code should be including that. 

However, that behavior used to work before (KotlinPoet was skipping emitting imports that didn't have a package name) and so it was ok not supplying the package for the default packages as well as classes that were referenced in the same package but now it is required to pass the package name. 

I understand that I was using it incorrectly before and should have been passing fully qualified names all along, but it gave the impression that KotlinPoet did honor default imports. I'm ok with making these changes on my consuming side but I do feel that this was an inadvertent breaking change.

**Comment by Egorand** [comment]
#636 fixed an issue that was making it impossible to use types declared in the default package. The new behavior is also semantically correct. Agree that it's a breaking change and I feel like most use-sites in the wild take advantage of the old hacky behavior, so it'll break them. Should we revert and postpone this until 2.0?

**Comment by JakeWharton** [comment]
I don't think we knew anyone was using it in this manner. In Java you cannot reference types in the default package explicitly so the code was likely inherited from JavaPoet (where I suppose you also could use it in the way you describe). From KotlinPoet's perspective this was just a bug fix that should have only affected those importing types in the default package.

> Should we revert and postpone this until 2.0?

I would vote no because then you're just going to cause a breaking change to someone who wanted to import a type from the default package. All bug fixes are breaking change when you rely on them. If the API is compatible, I prefer moving the library towards the correct behavior which is what that PR did.

**Comment by shaishavgandhi05** [comment]
I'm ok with moving forward instead of reverting (i.e find a way to maybe make both work?). 

I'd also like to point out that the change in question hasn't really landed to anyone yet (it was after 1.1.0 release). I only discovered it since I was using SNAPSHOT to get some bugfixes in. We're more likely to know if other people are using it after 1.2.0 is released.

**Comment by Egorand** [comment]
I doubt there's a way to make both work, since the old way is incorrect and the new way is correct. Unless your `FileSpec` is in the `kotlin` package, it's only correct to use `ClassName("kotlin", "IntArray")` to get the proper import. 

Pretty sure we'll break someone's code when we release 1.2, but I tend to agree with Jake - a bug fix that breaks semantically incorrect code should not be considered a breaking change.

**Comment by JakeWharton** [comment]
Depending on what you're doing, _you_ can probably make the old way work by just assuming the `kotlin` package for unqualified types from whatever your input is. Or, if you're relying on the multiple packages which are imported by default, maintain a list of types in those packages and match on their simple name to produce their package. This will allow you to take `IntArray` and get a `ClassName("kotlin", "IntArray")` from it.

**Comment by shaishavgandhi05** [comment]
Yeah you're right. There's no point supporting a wrong API usage. I've worked around my issue with using packages with `bestGuess`. Thankfully, wasn't too bad. Thanks for the suggestions!
