### ISSUE TITLE
[Question] Extend Generic Abstract Class

### ISSUE THREAD

**Issue by depressingillusion** [square/kotlinpoet#704]
If I wanted to have a signature of
```
class Foo: Bar<Barz>
```
how would i go about that. i tried to do something like
```
TypeSpec.classBuilder("Foo")
    .superclass(ClassName("", "Bar").???)
```
I think I need to do something like ``.parematerizedBy(Barz??)`` though I dont have this access to this method, as its not resolved, and I honestly just have no clue where to go from here. Any help is appreciated, thanks!

**Comment by Egorand** [comment]
`parameterizedBy()` is the way to go. You'll have to import it manually, auto-import doesn't work in this case due to an IDE issue (as described in our [README](https://github.com/square/kotlinpoet#t-for-types)).

In future please use [Stackoverflow](https://stackoverflow.com/questions/tagged/kotlinpoet) for questions, we use issue tracker for bug reports and feature requests only.

**Comment by depressingillusion** [comment]
Thanks, and alright. Just saw that there for a few questions posted in issues and thought it was correct to ask here. Cheers!
