### ISSUE TITLE
Potential bug when using lambdas, annotation & collections

### ISSUE THREAD

**Issue by vinaygaba** [square/kotlinpoet#908]
Firstly, thank you for even creating this library! I'm very grateful as it makes generating code super easy to do! 

I was using this library to generate the following code
```
val map: Map<String, @CustomAnnotation()() -> Unit>
```
Here's the KotlinPoet code that I used

```
val customAnnotationClassName = ClassName("package_path", "Annotation")
val customAnnotation = AnnotationSpec.builder(customAnnotationClassName).build()
val predicate = LambdaTypeName.get(returnType = UNIT).copy(annotations = arrayListOf(customAnnotation))
val mapType = Map::class.asClassName().parameterizedBy(String::class.asTypeName(), predicate)
val mapProperty = PropertySpec.builder("map", mapType).build()
```

and here's the code that it generated

```
val map: Map<String, @CustomAnnotation() @CustomAnnotation() -> Unit>
```

There are a couple issues here:
- It's showing the name of the annotation twice
- Instead of the annotation showing up twice, I need the round brackets to show up twice`@CustomAnnotation()() -> Unit`

Is there a better way to generate this code?

**Comment by ZacSweers** [comment]
Looks like this is a bug. Want to send a PR?

**Comment by Egorand** [comment]
There's indeed a couple issues I've noticed:

1. The annotations are indeed emitted twice, first by the `ParameterizedTypeName` (representing `Map<String, @CustomAnnotation() () -> Unit>`) and then the `LambdaTypeName` (representing `@CustomAnnotation() () -> Unit`). IMO, `ParameterizedTypeName` should not emit its parameters' annotations, but let's see if removing that line of code (`TypeName:622`) breaks any tests.
2. We won't emit the trailing `()` after the annotation name if it doesn't have parameters. I'm not sure we should fix this, given that it's a Kotlin bug ([KT-31734](https://youtrack.jetbrains.com/issue/KT-31734)) that is fixed in 1.4. There's also a compiler flag that as I understand removes the compilation error in 1.3.

**Comment by JakeWharton** [comment]
I'm a no on number 2 as well.

**Comment by vinaygaba** [comment]
Thank you @Egorand for your detailed response. 
I tried simply removing the line you suggested and I'm seeing the following failures

```
com.squareup.kotlinpoet.jvm.JvmAnnotationsTest > jvmWildcardType FAILED
    com.google.common.truth.ComparisonFailureWithFacts at JvmAnnotationsTest.kt:579

com.squareup.kotlinpoet.jvm.JvmAnnotationsTest > jvmSuppressWildcardsType FAILED
    com.google.common.truth.ComparisonFailureWithFacts at JvmAnnotationsTest.kt:560

com.squareup.kotlinpoet.AnnotatedTypeNameTest > annotatedArgumentOfParameterizedType FAILED
    org.junit.ComparisonFailure at AnnotatedTypeNameTest.kt:69

com.squareup.kotlinpoet.KotlinPoetTest > importTypeArgumentInParameterizedTypeName FAILED
    com.google.common.truth.ComparisonFailureWithFacts at KotlinPoetTest.kt:687

740 tests completed, 4 failed, 40 skipped
```

**Comment by vinaygaba** [comment]
Seems like there needs to be a way to know when an annotation was already added. Are there any existing examples in the library where this is handled elegantly?
