### ISSUE TITLE
KModifier.REIFIED currently isn't used at all

### ISSUE THREAD

**Issue by enjoydambience** [square/kotlinpoet#974]
Right now reified type parameters are represented by isReified in TypeParameterName, and the KModifier isn't used at all.

I suggest either:
- Since a type parameter can only be one of `in`, `out`, or `reified`; add a `modifier` property to TypeParameterName, deprecate the `isReified` and `variance` properties (and delegate behavior to the new property) and remove in 2.0
- Remove KModifier.REIFIED and document appropriately

I'm leaning towards the first option

**Comment by Egorand** [comment]
I don't think that creating a use case for `KModifier.REIFIED` is a good enough reason to change the API. Are there any issues with how `TypeParameterName` is designed?

`KModifier` represents the complete set of Kotlin modifiers and the lack of internal usages of any of `KModifier` values isn't a reason to delete it from the set - library consumers might have legitimate use cases for them.

**Comment by enjoydambience** [comment]
Its seems weird how the `reified` modifier is handled differently than how modifiers are used in the rest of the API, in its own wierd, ad-hoc way. Meanwhile the seemingly most obvious way to use reified is `KModifier.REIFIED`, which is instead not used at all. This is rather surprising to api consumers.

Furthermore, the change mentioned previously can be done in a backwards compatible fashion.
The old properties `isReified` and `variance` don't strictly need to be removed either.

**Comment by Egorand** [comment]
So the proposition here is to go from `isReified` and `variance` to `addModifier` (or probably `setModifier`, since you can only have one IIRC)? I think this is worse as it'll enable calls such as `TypeVariableName.addModifier(KModifier.EXPECT)` that look legit by the looks of them but we'll have to defend against at runtime. You can make an argument that `variance = KModifier.EXPECT` also compiles, but at least it's easy to spot by just looking at the expression. Spec builders that have `addModifier` methods usually accept a large number of modifiers, hence it's easier to capture all of them with a single method rather than introducing a designated setter for each.

**Comment by Egorand** [comment]
Closing, I don't think there's anything for us to do here.
