### ISSUE TITLE
Provide an easier method of using primary constructor properties

### ISSUE THREAD

**Issue by enjoydambience** [square/kotlinpoet#975]
Right now adding primary constructor properties requires using two different builders and takes a lot of rather repetitive code.
There should be a easier way of adding primary constructor properties, as primary constructor properties are rather common. Making data classes or annotation classes becomes rather cumbersome as all parameters need to be val/var parameters.

Some ideas on how to do this:
- Introduce a new function(s) to `FunSpec.Builder` (as constructor) and/or `TypeSpec.Builder`
- Maybe use `PropertySpec`s for these parameters (and check they have no custom getter/setter)

Currently, to produce:
```kotlin
data class Foo(val a: String, var b: Int, val c: Boolean)
```
Requries:
```kotlin
TypeSpec.classBuilder("Foo")
    .addModifiers(KModifier.DATA)
    .primaryConstructor(FunSpec.constructorBuilder()
        .addParameter("a", String::class)
        .addParameter("b", Int::class)
        .addParameter("c", Boolean::class)
        .build())
    .addProperty(PropertySpec.builder("a",String::class)
        .initializer("a")
        .build())
    .addProperty(PropertySpec.builder("b", Int::class)
        .initializer("b")
        .mutable()
        .build())
    .addProperty(PropertySpec.builder("c", Boolean::class)
        .initializer("c")
        .build())
    .build()
```
Versus something which could be like:
```kotlin
TypeSpec.classBuilder("Foo")
    .addModifiers(KModifier.DATA)
    .primaryConstructor(FunSpec.constructorBuilder()
        .addValParameter("a", String::class)
        .addVarParameter("b", Int::class)
        .addValParameter("c", Boolean::class)
        .build()
).build()
```

**Comment by JakeWharton** [comment]
The current design is deliberate. I would be opposed to this API as sketched.

Where do defaults live? Where do annotations live? What happens if you need to modify the constructor argument before storing it into the backing field behind a property?

The current design emits a collapsed primary constructor as an optimization but you never design your generated code in that way. It happens automatically when you build the right shape. And most importantly, it means as soon as you need to tweak something which breaks that optimization you aren't replacing one entire mechanism with another.

**Comment by JakeWharton** [comment]
I remembered another justification: you write the verbose KotlinPoet code once and it generates the compact code hundreds or thousands of times. This is in stark contrast to if you were writing the generated source manually in which case the compact form is what you want to write simply because it's less boilerplate. We don't mind causing boilerplate that only occurs once.

**Comment by enjoydambience** [comment]
I should have refined my argument earlier:

Annotation classes, data classes, and inline classes, _require_ primary constructor properties. In those cases, it is always desired for all primary constructor parameters to be properties. The current way to do this is quite verbose, and also does not provide verification that a primary constructor parameter is actually created. A method that explicitly states and checks that a primary constructor property is being added would be useful in this situation.

In other cases, if the API consumer requires more flexibility in properties/parameters, they can use the more verbose syntax.

The syntax does not have to be like the one sketched earlier.
Perhaps it would make more sense to put the functionality on `TypeSpec.Builder`.

**Comment by Egorand** [comment]
@JakeWharton want to respond and close the issue if there's no action to take?

**Comment by JakeWharton** [comment]
> Annotation classes, data classes, and inline classes, _require_ primary constructor properties

But all of those permit non-primary properties, so there will still be the need to support both on those types. There are lots of things that are required when generating code which we can't enforce in the API and we don't try to. The compiler is ultimately the source of truth for what is and what isn't valid.

> A method that explicitly states and checks that a primary constructor property is being added would be useful in this situation.

Because a primary constructor property is an optimization, you can achieve this with an extension function on the builder types. I think for now experimenting with this is the best route to take. We say no to a lot of things because we want to keep the core small, and there is a surprising amount of design work to support something like this. A primary constructor property is not just a name and a type, but it can host all kinds of syntactical elements that need a place to live which means supporting those may get as complicated as creating them the current way.

Perhaps down the road we will support this given something of sufficient design, but as proposed the feature it not fully developed and since we have no desire to add this ourselves. If you want to keep designing this as extension functions and even publish them as a companion library we would welcome that. This has also occurred with JavaPoet for similar reasons.
